### ISSUE TITLE
Add properties for points/shapes

### ISSUE THREAD

**Issue by kevinyamauchi** [wahlby-lab/napari-tissuumaps#1]
Hello! As we discussed on the call last Friday, napari supports annotating items in the points, labels, and shapes layers. These annotations are called "properties" and are typically used for annotations such as the name of the gene a point corresponds with or some metadata about a region of interest. I think it could be nice if these annotations could be loaded into tissuumaps.

The properties are a table where each row is index matched to the layer data and each column is a different annotation. The table is stored as a dictionary where each key is a column name  (string) and each value contains the corresponding column values as a numpy array. For example, this table

| confidence | good_point |  
|------------|------------|
| 1          | True       |
| 0.5        | False      | 
| 0          | False      | 

would be stored as

```python
{
    'confidence': np.array([1, 0.5, 0]),
    'good_point': np.array([True, False, False])
}
```

The properties table can be used to set colors and text associated with a given point/shape. See this p[oints example](https://github.com/napari/napari/blob/main/examples/add_points_with_properties.py) and this [shapes example](https://github.com/napari/napari/blob/main/examples/add_shapes_with_text.py) for some example implementations.

You can access the properties via the `layer.properties` getter method. If you would like to get the value of all of the layer's state variables can use `layer._get_state()`. Also, I believe you can get the output of `layer._get_state()` as part of the layer data that is passed to your writer hook implementation (see docs [here](https://napari.org/docs/0.3.8/plugins/hook_specifications.html#napari.plugins.hook_specifications.napari_get_writer)).

```python
import json

import numpy as np
import pandas as pd
from skimage import data
from skimage.color import rgb2gray
import napari


# add the image
viewer = napari.view_image(rgb2gray(data.astronaut()))
# add the points
points = np.array([[100, 100], [200, 200], [333, 111]])

# create properties for each point
properties = {
    'confidence': np.array([1, 0.5, 0]),
    'good_point': np.array([True, False, False])
}

# define the color cycle for the face_color annotation
face_color_cycle = ['blue', 'green']

# create a points layer where the face_color is set by the good_point property
# and the edge_color is set via a color map (grayscale) on the confidence property.
points_layer = viewer.add_points(
    points,
    properties=properties,
    size=20,
    edge_width=7,
    edge_color='confidence',
    edge_colormap='gray',
    face_color='good_point',
    face_color_cycle=face_color_cycle
)

# print the layer properties
print(points_layer.properties)

# save the properties as a csv
df = pd.DataFrame(points_layer.properties)
df.to_csv('my_properties.csv')

# get the current layer state
layer_state = points_layer._get_state()
```

**Comment by npielawski** [comment]
Hello Kevin!

I implemented the properties for both the points and shapes, even if TissUUmaps doesn't support shapes prop. at the moment, at least the information is not lost.

As you can see in the screenshot below, I loaded ~400k points in Napari, with a color property depending on the quality of detection and exported the project to TissUUmaps:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/11574848/133399522-4ff6bbb5-93e0-4623-b257-aee18b2aad83.png">

And a zoomed in version:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/11574848/133399117-73416d63-b900-47e2-9586-2fa90581801d.png">

The images and points run smoothly in both Napari and TissUUmaps which is nice.
